service: product

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: '/product'
          method: 'get'
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: '/product/{id}'
          method: 'get'
          cors: true
