service: product

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi: 'GET /products'
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi: 'GET /products/{id}'
